In [5]:
import numpy as np

def create_block_matrix(*matrices):
    
    num_matrices = len(matrices)
    
    
    matrix_size = matrices[0].shape
    for matrix in matrices:
        if matrix.shape != matrix_size:
            raise ValueError("Input matrices must have the same shape.")
    
    n = matrix_size[0]  
    
    
    block_matrix = np.zeros((n * num_matrices, n * num_matrices), dtype=matrices[0].dtype)
    
    
    for i in range(num_matrices):
        for j in range(num_matrices):
            block_matrix[i*n:(i+1)*n, j*n:(j+1)*n] = matrices[(i+j) % num_matrices]
    
    return block_matrix


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

block_result = create_block_matrix(A, B)
print(block_result)


[[1 2 5 6]
 [3 4 7 8]
 [5 6 1 2]
 [7 8 3 4]]


In [6]:
import numpy as np

def create_block_matrix(*matrices):
    # 入力行列の数を取得
    num_matrices = len(matrices)
    
    if num_matrices == 0:
        raise ValueError("At least one input matrix is required.")
    
    # 各行列のサイズを確認し、一致しない場合はエラーを発生させる
    matrix_size = matrices[0].shape
    for matrix in matrices:
        if matrix.shape != matrix_size:
            raise ValueError("Input matrices must have the same shape.")
    
    n = matrix_size[0]  # 各行列のサイズ
    
    # ブロック行列を初期化
    block_matrix = np.zeros((n * num_matrices, n * num_matrices), dtype=matrices[0].dtype)
    
    # ブロック行列に行列を配置
    for i in range(num_matrices):
        for j in range(num_matrices):
            block_matrix[i*n:(i+1)*n, j*n:(j+1)*n] = matrices[(i+j) % num_matrices]
    
    return block_matrix

# 使用例
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

block_result = create_block_matrix(A, B, C, C, C)
print(block_result)


[[ 1  2  5  6  9 10  9 10  9 10]
 [ 3  4  7  8 11 12 11 12 11 12]
 [ 5  6  9 10  9 10  9 10  1  2]
 [ 7  8 11 12 11 12 11 12  3  4]
 [ 9 10  9 10  9 10  1  2  5  6]
 [11 12 11 12 11 12  3  4  7  8]
 [ 9 10  9 10  1  2  5  6  9 10]
 [11 12 11 12  3  4  7  8 11 12]
 [ 9 10  1  2  5  6  9 10  9 10]
 [11 12  3  4  7  8 11 12 11 12]]


In [75]:
import numpy as np

def create_block_matrix(matrices):
    n = len(matrices)
    if n == 0:
        return None

    rows, cols = matrices[0].shape
    block_rows = n * rows
    block_cols = n * cols

    block_matrix = np.zeros((block_rows, block_cols))

    for i in range(n):
        for j in range(n):
            block_matrix[i * rows:(i + 1) * rows, j * cols:(j + 1) * cols] = matrices[(j - i) % n]

    return block_matrix

# 例: A, B, C, D, E を行列として作成
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])
D = np.array([[13, 14], [15, 16]])
E = np.array([[17, 18], [19, 20]])

# 行列をリストにまとめて、指定されたパターンで block 行列を生成
matrices = [A, B, C, D, E]
block_matrix = create_block_matrix(matrices)

F = np.array([[13, 14, 16], [15, 16, 19]])
G = np.array([[17, 18, 20], [19, 20, 11]])

block_matrix_1 = create_block_matrix([F,G])


N_0 =len(A)

N = 2

N_1 = (N+1) * N_0
print(N_1)
print(block_matrix[:N_1, :N_1])
print(block_matrix_1)

6
[[ 1.  2.  5.  6.  9. 10.]
 [ 3.  4.  7.  8. 11. 12.]
 [17. 18.  1.  2.  5.  6.]
 [19. 20.  3.  4.  7.  8.]
 [13. 14. 17. 18.  1.  2.]
 [15. 16. 19. 20.  3.  4.]]
[[13. 14. 16. 17. 18. 20.]
 [15. 16. 19. 19. 20. 11.]
 [17. 18. 20. 13. 14. 16.]
 [19. 20. 11. 15. 16. 19.]]


In [8]:
import numpy as np

N = 4  
matrix = np.array([[1, 2, 3, 1, 2, 3],
                   [4, 5, 6, 1, 2, 3],
                   [7, 8, 9, 1, 2, 3],
                   [7, 8, 9, 1, 2, 3],
                   [7, 8, 9, 1, 2, 3]])

matrix = matrix[:N+1, :N+1]

print(matrix)

[[1 2 3 1 2]
 [4 5 6 1 2]
 [7 8 9 1 2]
 [7 8 9 1 2]
 [7 8 9 1 2]]


In [76]:
import numpy as np

N = 3
n = 2
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[5, 6], [7, 8]]])

AA = [A[i, :, :] for i in range(N)]
AA[1].shape
AA

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[5, 6],
        [7, 8]])]

In [71]:
print(create_block_matrix(AA))

[[1. 2. 5. 6. 5. 6.]
 [3. 4. 7. 8. 7. 8.]
 [5. 6. 1. 2. 5. 6.]
 [7. 8. 3. 4. 7. 8.]
 [5. 6. 5. 6. 1. 2.]
 [7. 8. 7. 8. 3. 4.]]


In [67]:
import numpy as np

# リストの作成
my_list = [1, 2, 3, 4, 5]

# リストをNumPyの配列に変換
#my_array = np.array(my_list)

# 配列を表示
print(isinstance(AA[1], np.ndarray))

True
